[package]
name = "redox-tui"
version = "0.5.1"
edition = "2024"
description = "TUI frontend runtime for redox-editor"
license = "MIT"
repository = "https://github.com/JackDerksen/redox"
readme = "README.md"
keywords = ["editor", "tui", "terminal", "vim", "text"]
categories = ["command-line-utilities", "text-editors"]

[[bin]]
name = "redox"
path = "src/main.rs"

[dependencies]
redox-core = { version = "0.5.1", path = "../redox-core" }
minui = { version = "0.7.1", features = ["clipboard"] }
anyhow = { workspace = true }
unicode-segmentation = "1.11.0"
tree-sitter = "0.26.7"
tree-sitter-c = "0.24.1"
tree-sitter-cpp = "0.23.4"
tree-sitter-css = "0.25.0"
tree-sitter-go = "0.25.0"
tree-sitter-html = "0.23.2"
tree-sitter-javascript = "0.25.0"
tree-sitter-json = "0.24.8"
tree-sitter-lua = "0.5.0"
tree-sitter-md = "0.5.3"
tree-sitter-python = "0.25.0"
tree-sitter-rust = "0.24.0"
tree-sitter-toml-ng = "0.7.0"
tree-sitter-typescript = "0.23.2"
tree-sitter-yaml = "0.7.2"
ignore = "0.4"
